# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: etl
      url-base: https://github.com/ETLCPP
    - name: lua
      url-base: https://github.com/tenllado


  #
  # Please add items below based on alphabetical order
  projects:
    - name: zephyr
      remote: upstream
      repo-path: zephyr
      revision: main
      import: true
      path: zephyr
      import:
        path-prefix: deps
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_atmel # required by the custom_plank board (Nordic based)
          - hal_stm32  # required by the nucleo_f302r8 board (STM32 based)
          - hal_st  # required by the nucleo_f302r8 board (STM32 based)
          - hal_espressif  # required by the nucleo_f302r8 board (STM32 based)
          - hal_xtensa  # required by the nucleo_f302r8 board (STM32 based)
          - lvgl
          - mbedtls
          - mcuboot

    - name: etl_base
      remote: etl
      repo-path: etl
      revision: 20.36.1
      path: deps/modules/etl

    - name: lua_base
      remote: lua
      repo-path: lua
      revision: zephyr
      path: deps/modules/lua

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml